### ISSUE TITLE
Lockup resuming from suspend with nvidia selected

### ISSUE THREAD

**Issue by Kisil** [JackHack96/dell-xps-9570-ubuntu-respin#11]
First, thanks for your work on this. I spent a couple of days fighting with my wife's identical 9570 before finding your image, and so far, mine is running much better.

Suspend works if I `sudo prime-select intel`. However, with `prime-select nvidia`, the laptop hangs on resuming from suspend: I get a black screen with one log line:
`[timestamp] rtc_cmos 00:01: Alarms can be up to one month in the future`
There's also a row of pixels at the bottom of the screen that shows a repeated pattern of noise. I get a similar distortion in that row on a fresh boot, and that goes away less than a minute after login.

So far, I've made only cosmetic tweaks. Besides automatically updated packages, I have the configuration from the prepared ISO. Current kernel is 4.17.9. The wiki suggests a "Force S3" option in the BIOS, but I don't have that option available. Also possibly relevant: I missed the chance to auto-install the new MOK after the first reboot, and haven't yet figured out how to repeat that process. So I'm still running in insecure mode.

**Comment by jhe-** [comment]
Indeed, thank you for making this JackHack96!

The row of pixels disappeared for me after reverting one of the experimental graphics optimizations mentioned in the wiki ([`--enable_psr=2`](https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/wiki/Troubleshooting), be sure to run `sudo update-initramfs -u` afterwards).

I have the same issue with the resuming from suspend when using NVIDIA. As for the `rtc_cmos` alarms printout, it's possible that it's not the root cause but rather an incidental print that persists due to the hang. I recall seeing the same message inside `dmesg` even when Intel was selected, and [`hwclock --systohc --localtime`](https://askubuntu.com/questions/175452/hwclock-not-in-sync-with-system-clock) seemed to fix that discrepancy though I still hang on resume in NVIDIA without the printout.

**Comment by mlopezantequera** [comment]
Hi, thanks for the respin, almost a 100% smooth experience!

Just chiming in: I also have problems resuming when the GPU is on.

**Comment by JackHack96** [comment]
I'm having problems with suspend on nvidia too. I'll try to research a bit, but it seems a deeper problem (see [here](https://devtalk.nvidia.com/default/topic/1032482/optimus-on-ubuntu-18-04-is-a-step-backwards-but-i-found-the-first-good-solution/?offset=66))

**Comment by Kisil** [comment]
Have you experimented with bumblebee at all? It seems like that might be the best place in the trade-off space - leaving Intel selected most of the time, and using optirun or primusrun to kick off graphics-intensive jobs. But I've done a bunch of reading and no two authors agree on what settings work or whether they actually do, and I so far haven't gotten it working on my wife's machine.

**Comment by Kisil** [comment]
Breadcrumbs for future passers-by.
Bumblebee configuration changes for nvidia drivers >390:
https://bugs.launchpad.net/ubuntu/+source/bumblebee/+bug/1758243
Some guy's bbswitch tutorial:
https://www.youtube.com/watch?v=5nGbWE-pvIE&t=433s
CUDA-centric setup for the 9560:
https://gist.github.com/whizzzkid/37c0d365f1c7aa555885d102ec61c048

There's a bunch more out there but I think these are the best starting points.

**Comment by jhe-** [comment]
> The wiki suggests a "Force S3" option in the BIOS, but I don't have that option available.

For what it's worth, bios 1.2.2 and earlier do have this option available, and for me it fixes suspend on nvidia. The system takes longer to wake up presumably due to S3, but it does wake up.

Dell removed this setting in 1.3.0, claiming it was redundant because they think S3 and "modern standby" are the same thing, much to our chagrin. If you are able to downgrade, try 1.2.2, and if you don't have 1.3 yet, I advise against it unless you need the other fixes.

https://www.dell.com/community/XPS/XPS-9570-BIOS-Sleep-Mode-Gone/td-p/6131926
http://forum.notebookreview.com/threads/xps-15-9570-owners-thread.817008/page-81#post-10773467
https://www.reddit.com/r/Dell/comments/91313h/xps_15_9570_c_state_bug_after_s3_sleep_and_modern/

**Comment by mabynke** [comment]
I had this problem and fixed it by following these instructions:
https://devtalk.nvidia.com/default/topic/969433

Maybe some of this could be incorporated in the respin?

**Comment by JackHack96** [comment]
I'll try that in the next week. If it works, I'll be integrating the fixes in the respin

**Comment by arbiter1elegantiae** [comment]
@mabynke method worked for me too, yet I dont know if every step was necessary too.

**Comment by jhe-** [comment]
The method linked to by @mabynke did not work for me, despite doing all five steps exactly. I'm on kernel 4.17.9, maybe you guys are on newer versions.

**Comment by JackHack96** [comment]
Today I've tried setting up bumblebee following the links of @Kisil, but without luck :cry:

**Comment by mabynke** [comment]
After a few days of using the computer, it appears that the method I linked to didn't fix it completely. The computer still sometimes fails to resume correctly. :slightly_frowning_face:

**Comment by Kisil** [comment]
Confirmed: adding `mem_sleep_default=deep` to my (long and growing!) grub config seems to fix sleep in both intel and nvidia mode. (I hadn't realized that sleep was broken in intel mode as well, but when I opened my laptop to test this, it was completely dead.)

journalctl now reports deep sleep in both modes, and I'm not crashing waking up from sleep in nvidia mode any more.

**Comment by JackHack96** [comment]
I'll add it in the ISO respin script

**Comment by mabynke** [comment]
Undoing what I did previously and adding `mem_sleep_default=deep` as mentioned by @Kisil didn't work for me. The fans don't turn off when I try to suspend, and when resuming again, I get a black screen with a single «_» in the top left corner. At least most of the time – it is a bit unpredictable.

**Comment by mabynke** [comment]
Undoing what I did previously and adding `mem_sleep_default=deep` as mentioned by @Kisil didn't work for me. The fans don't turn off when I try to suspend, and when resuming again, I get a black screen with a single «_» in the top left corner. At least most of the time – it is a bit unpredictable.

EDIT: Please disregard! I made a mistake in my /etc/default/grub. I fixed it now, and does indeed seem to work on NVIDIA. Will test on Intel as well and report back if something is wrong.

**Comment by chenmin1107** [comment]
The newest ISO repin has this line added "mem_sleep_default=deep". However, I still can not resume from suspend when nvidia is used. Any suggestions? Thanks!
