### ISSUE TITLE
Laptop goes off randomly when typing

### ISSUE THREAD

**Issue by rrupam** [JackHack96/dell-xps-9570-ubuntu-respin#129]
I have been using this laptop since January. Since a few days, the laptop will just shut down abruptly when typing - not specific key combinations necessarily, although it does shut down very often when using ctrl + alt or shift + $. I spoke to dell support and it seems like there is no hardware issues, but could be an ubuntu problem.

**Comment by JackHack96** [comment]
Woah this is weird!
Maybe a look at `/var/log/syslog` would be useful

**Comment by rrupam** [comment]
Thanks for your response. Sorry -- is this project not related to ubuntu on dell-xps-9570? 

Update: I upgraded to UBuntu 19.10 and since then its much better, but was still going off at ctrl + alt yesterday. Today, its not going off at ctrl + alt either. In the var/log/syslog file, I see several events like 'Core temperature above threshold, cpu clock throttled'. These occur at least since the the day before when I was facing the sudden off problem and even till a half hour back, although the laptop hasn't shut off by itself at all today. This doesn't look normal to me, but I don't know what could be causing it.

**Comment by JackHack96** [comment]
This project is just a collection of tweaks for making Ubuntu running better on the XPS 9570 :smile: 
What I meant is that I think this bug is not inherent to the tweaks :)
Anyway, good to hear that with 19.10 is going better.

The fact that you can see the "core temperature" message is not very relevant since many of us face this issue due to the bad thermal management of the laptop, so the only thing I could suggest you would be to freshly install a copy of Ubuntu 20.04, which will be released next week (or you can install a daily build, I'm using them for two weeks now), after backing up all the data.
It may be a long process depending on the amount of data, but I can't suggest anything else, sorry :(
