### ISSUE TITLE
Sound stopped working

### ISSUE THREAD

**Issue by dvatsal** [JackHack96/dell-xps-9570-ubuntu-respin#136]
My speaker of laptop has stopped working and headphone jack works in windows and does not work in Ubuntu.

What can be the issue and resolution?

Please advise

**Comment by JackHack96** [comment]
Have you tried first a generic troubleshooting?
Like the steps described in this article https://www.maketecheasier.com/fix-no-sound-issue-ubuntu/

**Comment by geisterfurz007** [comment]
I had a similar issue. I needed to plug my headset in several times until I got prompted what kind of device I plugged in. After selecting Headset, I need to go to Settings > Sound and select "Headphones - Built-in Audio" as Output and "Headset Microphone - Built-in Audio" as Input. Since then I didn't have issues (other than having to set these things each time I plug in the same headset again).
