### ISSUE TITLE
Unable to boot

### ISSUE THREAD

**Issue by littlejuice** [JackHack96/dell-xps-9570-ubuntu-respin#29]
Hello !

Thanks for the work provided :)
I'm feeling so happy that I'm not the only guy who tried to use Linux on this laptop.

Unfortunately, I have an issue after installing Ubuntu with the respin usb key.
The installation worked pretty well, but when I reboot, I'm not able to join the grub. Each times I tried, I have the "dell support assist", which tries to scan my hardware. 

I've done a full ubuntu installation (no dual boot and wiped the disk) and really can't understand why I'm not able to boot it after the installation is done. I've tried serveral methods (F12 boot, modified some Boot parameters in the BIOS, re-install the key...) with no success. May you could help me ?

Thanks !

**Comment by harche** [comment]
Same issue.

**Comment by harche** [comment]
@JackHack96 any clue?

**Comment by JackHack96** [comment]
That's weird. First of all, check for Secure Boot. I have disabled it because it only make things worse. Then make sure you installed Ubuntu with the GPT partition scheme (you have to make it manually, follow this guide if you don't know how to do it: [https://askubuntu.com/questions/743095/how-to-prepare-a-disk-on-an-efi-based-pc-for-ubuntu/743098#743098](https://askubuntu.com/questions/743095/how-to-prepare-a-disk-on-an-efi-based-pc-for-ubuntu/743098#743098)).
After you have correctly installed it, the BIOS should see the Ubuntu partition, so make it the first and it should work ;)

**Comment by harche** [comment]
Thanks, that worked. For some reason, the ubuntu installed wiped out the EFI partition. I had to manually create it again and everything worked just fine.
