### ISSUE TITLE
pre-built iso hangs on "Detecting file systems" -- one hour, then black screen, fan running intermittently

### ISSUE THREAD

**Issue by rsspdx** [JackHack96/dell-xps-9570-ubuntu-respin#55]
I'm trying a second time with the same results. I fixed the BIOS so it booted properly (disable Secure Boot, enable Legacy ROM / external device. Now it's hanging. Any ideas? Or is this expected ...  Thanks for all your help.

**Comment by JackHack96** [comment]
No it shouldn't do like that. I'll try to test it outside a VM...

**Comment by JackHack96** [comment]
Ok I confirm it's not working! It does a kernel panic :cry: 
It will take a while to understand why

**Comment by SylvainLan** [comment]
Do you recommend to install ubuntu with the official iso and then fix it when it is installed then ?

**Comment by JackHack96** [comment]
For now, yes

**Comment by SylvainLan** [comment]
I'll do that, thanks !

**Comment by jungla88** [comment]
I have got the same issue and It happen when it wants to load nvidia module on boot.
I bypass the problem in installation just typing CTRL+C during that phase. 
First boot will fail with the same problem. Then I start in recovery mode and purge all nvidia stuff. 
After that I can login with intel driver. You can try to reinstall nvidia driver now.

**Comment by Xparx** [comment]
Just want to add that I am also experiencing a hang after booting up when it start to unload nvidia modules. or something to that effect. The text flashes to fast to actually read anything.

**Comment by Xparx** [comment]
I also noticed that in the install description the preparation of the bios settings is not spelled out. As OP spells out here some steps are needed. On top of the legacy boot/ secure boot things. Should I modify the grub boot in some way for the official install? e.g.
nouveau.modeset=0

**Comment by JackHack96** [comment]
I should have fixed it in the pre-built ISO. I just tested the live on my XPS and it's working correctly!

@Xparx SecureBoot can be enabled, though I disable it because I don't want to wait 10 seconds at every boot for the MOK management thing

**Comment by jungla88** [comment]
I used the prebuilt ISO and it was not possible to load the live os. Installation work as I mentioned before.
For sake of completeness my XPS 15 9570 comes with i5 8th gen and Nvidia 1050(not Ti).

**Comment by Xparx** [comment]
I see. I disabled secure boot and it seems ok for me. I ended up using your post install script but i'm not strictly sure if it was needed. I can't figure out how to make dual screens work but as long as I turn of the built in screen when I attach my monitor through my dock it seems to work.
My laptop seems unnecessarily hot as well which is a bit weird, not sure what that is about.

**Comment by JackHack96** [comment]
Uhm, that's not expected! Actually with Linux it should run colder than Windows xD

**Comment by Xparx** [comment]
Just to complete.
I haven't checked how hot it runs on windows. It might be comparable but I don't think it's much lower if it is. I noticed that when I boot up the laptop when the lid is closed. the warning led lights in front of the laptop starts blinking and I thought it was because the laptop was overheating but when redoing it when the laptop has been off for a while and is clearly cold the light still goes off. Not sure why this happens.

I noticed that when not connected to the charger the laptop drops about 15C as measured by sensors. from 70C to around 55-60C. 
I also noticed that when switching on the nvidia graphics card the temperature shoots up to around >70C as measured by sensors. (I say sensors specifically because the tlp-stats command gives a different temperature which is similar to processor temperature in sensors.)
I'm thinking that with the charger the on demand processor routine is different and focused on performance rather than when charger is not connected.

I just noticed these things anecdotally.

**Comment by Grybouilli** [comment]
Hello,
I've been trying to use the respun iso currently available in the readme but it seems like I'm facing the same issue discribed here (black screen, console going mad...)... any idea ?

**Comment by Xparx** [comment]
I tried the regular ubuntu iso and checked if had any issues. Optionally apply the shell script provided here post install. That worked for me.

**Comment by Grybouilli** [comment]
Thanks for the reply
I have a working iso, I think I'm gonna go for this option then
Should I add anything in the grub option (like nouveau.modeset=0) ?

**Comment by Xparx** [comment]
I did not need to do that.

**Comment by Grybouilli** [comment]
Okay, i'll try that a bit later, i'll keep you aware of the state of it
Thanks a lot!

**Comment by Grybouilli** [comment]
Haven't had much time to experience but everything seems stable !
