### ISSUE TITLE
Touchpad jumps

### ISSUE THREAD

**Issue by iamjackg** [JackHack96/dell-xps-9570-ubuntu-respin#76]
Hey there!

One thing I've noticed is that by default the install is using libinput for the touchpad. I know it's more modern, etc. but it was actually causing issues for me: the cursor would occasionally jump to the other side of the screen, and two-/three-finger tap detection was very flakey.

All the issues were immediately solved by installing the synaptics drivers (and keeping libinput installed for keyboard handling).

I'm wondering if anybody else has seen the same behaviour? If there's enough supporting evidence, I can probably put together a pull request, but I first want to make sure I'm not the only one experiencing this.

**Comment by JackHack96** [comment]
Uhm, I never experienced this issue sincerely

**Comment by iamjackg** [comment]
Interesting! I wonder what causes this variance in user experience.

**Comment by JackHack96** [comment]
Did you try [this](https://www.dell.com/support/article/it/it/itdhs1/sln308258/precision-xps-ubuntu-general-touchpad-mouse-issue-fix?lang=en)?

**Comment by iamjackg** [comment]
I did, but that page is _very_ odd: it first tells you to blacklist one of the two entries or "synclient will get confused", but then it guides you through _uninstalling_ the synaptics drivers and switching to libinput instead. :thinking: Which is the opposite of what I did to solve my issue.

Dell continues to be an endless source of mysteries!

**Comment by floturcocantsee** [comment]
I haven't experienced this issue. Are you using the GNOME desktop? I know KDE has real shoddy support for multitouch touchpads.

**Comment by SuperKam91** [comment]
@iamjackg how did you fix this out of curiosity? I did:
sudo apt-get install xserver-xorg-input-libinput
sudo apt-get remove --purge xserver-xorg-input-synaptics

and unfortunately it hasn't resolved the issue.
Many thanks!

**Comment by floturcocantsee** [comment]
> @iamjackg how did you fix this out of curiosity? I did:
> sudo apt-get install xserver-xorg-input-libinput
> sudo apt-get remove --purge xserver-xorg-input-synaptics
> 
> and unfortunately it hasn't resolved the issue.
> Many thanks!

Probably related: https://gitlab.freedesktop.org/libinput/libinput/issues/36

**Comment by SuperKam91** [comment]
> > @iamjackg how did you fix this out of curiosity? I did:
> > sudo apt-get install xserver-xorg-input-libinput
> > sudo apt-get remove --purge xserver-xorg-input-synaptics
> > and unfortunately it hasn't resolved the issue.
> > Many thanks!
> 
> Probably related: https://gitlab.freedesktop.org/libinput/libinput/issues/36

I tried the fix relating to the tlp config mentioned in the comment below:

" Pierpaolo Valerio @pierpaolo.valerio · 6 months ago

After an inordinate amount of time spent troubleshooting this issue, I think I finally cracked it and it is not related to libinput at all. What happens is that some (most?) distros come with TLP enabled by default for power saving, and for some reason if you don't touch the touchpad for a couple of seconds it gets suspended. It then takes a long time "waking up", causing the cursor jumps. If I add the line RUNTIME_PM_BLACKLIST="00:15.1" to my /etc/default/tlp file, the issue goes away completely, as it disables power saving for the PCI-to-I2C controller connected to the touchpad. I haven't tested for long, but powertop tells me that the power consumption doesn't seem to be affected in any meaningful way. Of course if you don't use TLP but powertop or other power saving tools, a similar solution can be adapted. Do I have to report this bug somewhere else since it's not libinput-related?"

But found that it didn't help, maybe perhaps because I have powertop installed as well (and don't know how to do an equivalent fix for it. I tried looking in the 'tuneables' of powertop but wasn't sure if there was anything useful to disable here.
